modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/Ketheroth/Slots/issues"

[[mods]]
modId = "slots"
version = "${version}"
displayName = "Slots"
updateJSONURL = "https://ketheroth.com/mods/slots.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/slots"
logoFile = "logo.png"
authors = "Ketheroth"
description = '''
Earn new inventory slots with experience levels.
'''

[[dependencies.slots]]
	modId = "forge"
	mandatory = true
	versionRange = "[47,)"
	ordering = "NONE"
	side = "BOTH"
[[dependencies.slots]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.20.1,)"
	ordering = "NONE"
	side = "BOTH"
[[dependencies.slots]]
	modId = "resourcefullib"
	mandatory = true
	versionRange = "[${resourcefullib_version},)"
	ordering = "NONE"
	side = "BOTH"
[[dependencies.slots]]
	modId = "resourcefulconfig"
	mandatory = true
	versionRange = "[${resourcefulconfig_version},)"
	ordering = "NONE"
	side = "BOTH"